# Generated by Django 3.2.8 on 2021-10-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Oblast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierArticle', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('SKU', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('seller', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WarenHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lastChangedate', models.DateTimeField()),
                ('techSize', models.CharField(max_length=20)),
                ('barcode', models.CharField(max_length=20)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('totalPrice', models.IntegerField()),
                ('discountPercent', models.PositiveSmallIntegerField()),
                ('isSupply', models.BooleanField()),
                ('isRealization', models.BooleanField()),
                ('orderId', models.PositiveIntegerField()),
                ('promoCodeDiscount', models.PositiveSmallIntegerField()),
                ('warehouseName', models.CharField(max_length=20)),
                ('countryName', models.CharField(max_length=20)),
                ('oblastOkrugName', models.CharField(max_length=20)),
                ('regionName', models.CharField(max_length=20)),
                ('incomeID', models.PositiveIntegerField()),
                ('saleID', models.PositiveIntegerField()),
                ('odid', models.PositiveIntegerField()),
                ('spp', models.PositiveSmallIntegerField()),
                ('forPay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finishedPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priceWithDisc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nmId', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('IsStorno', models.BooleanField()),
                ('gNumber', models.PositiveIntegerField()),
                ('supplierArticle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ware')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lastChangedate', models.DateTimeField()),
                ('techSize', models.CharField(max_length=20)),
                ('barcode', models.CharField(max_length=20)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('totalPrice', models.IntegerField()),
                ('discountPercent', models.PositiveSmallIntegerField()),
                ('warehouseName', models.CharField(max_length=20)),
                ('oblast', models.CharField(max_length=20)),
                ('incomeID', models.PositiveIntegerField()),
                ('odid', models.PositiveIntegerField()),
                ('nmId', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('is_cancel', models.BooleanField()),
                ('cancel_dt', models.DateTimeField(auto_now_add=True)),
                ('gNumber', models.PositiveIntegerField()),
                ('supplierArticle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ware')),
            ],
        ),
    ]
