# Generated by Django 3.2.8 on 2021-10-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
