# Generated by Django 3.2.8 on 2021-10-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ware_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='sale',
            name='IsStorno',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='barcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='brand',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='countryName',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discountPercent',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='finishedPrice',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='forPay',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='gNumber',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='incomeID',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='isRealization',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='isSupply',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='lastChangedate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='nmId',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='oblastOkrugName',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='odid',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='orderId',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='priceWithDisc',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='promoCodeDiscount',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='regionName',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='saleID',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='spp',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='subject',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='techSize',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='totalPrice',
            field=models.IntegerField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='warehouseName',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ware',
            name='brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ware',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ware',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ware',
            name='seller',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
