# Generated by Django 3.2.8 on 2021-10-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211014_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='finishedPrice',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='forPay',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='lastChangedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='priceWithDisc',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='totalPrice',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
