# Generated by Django 3.2.8 on 2021-10-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211014_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='gNumber',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='incomeID',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='nmId',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='odid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='orderId',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='promoCodeDiscount',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='saleID',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='spp',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
