# Generated by Django 3.2.8 on 2021-10-14 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211014_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discountPercent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='supplierArticle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='api.ware'),
        ),
    ]
