# Generated by Django 3.2.8 on 2021-10-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211014_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='ware',
            name='supplierArticle',
            field=models.CharField(default=11111, max_length=10),
            preserve_default=False,
        ),
    ]
