# Generated by Django 3.2.8 on 2021-10-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_ware_supplierarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ware',
            name='supplierArticle',
        ),
    ]
