# Generated by Django 3.2.8 on 2021-10-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_ware_supplierarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='finishedPrice',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='forPay',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='spp',
        ),
        migrations.AlterField(
            model_name='sale',
            name='totalPrice',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
