# Generated by Django 3.2.8 on 2021-10-14 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_ware_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('discountPercent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('supplierArticle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.ware')),
            ],
        ),
    ]
