from django.db import models


class Order(models.Model):
    number = models.CharField(max_length=20, null=True)
    date = models.DateTimeField(auto_now_add=True, null=True)
    lastChangeDate = models.DateTimeField(blank=True, null=True)
    supplierArticle = models.CharField(max_length=20, null=True)
    techSize = models.CharField(max_length=20, null=True)
    barcode = models.CharField(max_length=20, blank=True)
    quantity = models.IntegerField(default=0, blank=True, null=True)
    totalPrice = models.IntegerField(default=0, blank=True, null=True)
    discountPercent = models.PositiveIntegerField(blank=True, null=True)
    warehouseName = models.CharField(max_length=20, null=True)
    oblast = models.CharField(max_length=20, null=True)
    incomeID = models.IntegerField(blank=True, null=True)
    odid = models.BigIntegerField(default=0, blank=True, null=True)
    nmId = models.PositiveIntegerField(blank=True, null=True)
    subject = models.CharField(max_length=20, null=True)
    category = models.CharField(max_length=20, blank=True, null=True)
    brand = models.CharField(max_length=20, blank=True, null=True)
    isCancel = models.BooleanField(default=0)
    cancel_dt = models.DateTimeField(blank=True, null=True)
    gNumber = models.CharField(max_length=20, null=True)


class Sale(models.Model):
    number = models.CharField(max_length=20, null=True)
    date = models.DateTimeField(auto_now_add=True, null=True)
    lastChangeDate = models.DateTimeField(blank=True, null=True)
    supplierArticle = models.CharField(max_length=20, null=True)
    techSize = models.CharField('Размер', max_length=20, blank=True)
    barcode = models.CharField('Штрихкод', max_length=20, blank=True)
    quantity = models.IntegerField('Количество продаж', default=0, blank=True, null=True)
    totalPrice = models.IntegerField('Цена без скидки', default=0, blank=True, null=True)
    discountPercent = models.PositiveIntegerField(blank=True, null=True)
    isSupply = models.BooleanField(blank=True, null=True)
    isRealization = models.BooleanField(blank=True, null=True)
    orderId = models.BigIntegerField(default=0, blank=True, null=True)
    promoCodeDiscount = models.PositiveIntegerField(blank=True, null=True)
    warehouseName = models.CharField(max_length=20, blank=True)
    countryName = models.CharField(max_length=20, blank=True)
    oblastOkrugName = models.CharField(max_length=20, blank=True)
    regionName = models.CharField(max_length=20, blank=True)
    incomeID = models.IntegerField(default=0, blank=True, null=True)
    saleID = models.CharField(max_length=20, null=True)
    odid = models.BigIntegerField(default=0, blank=True, null=True)
    spp = models.PositiveIntegerField('Цена СПП', blank=True, null=True)
    forPay = models.DecimalField(decimal_places=2, max_digits=10, blank=True, editable=False, null=True)
    finishedPrice = models.DecimalField(decimal_places=2, max_digits=10, blank=True, editable=False, null=True)
    priceWithDisc = models.DecimalField(decimal_places=2, max_digits=10, blank=True, editable=False, null=True)
    nmId = models.PositiveIntegerField('Наименование', blank=True, null=True)
    subject = models.CharField('Предмет', max_length=20, blank=True)
    category = models.CharField('Категория', max_length=20, blank=True, null=True)
    brand = models.CharField(max_length=20, blank=True, null=True)
    IsStorno = models.BooleanField(blank=True, null=True)
    gNumber = models.CharField(max_length=20, null=True)
