# Generated by Django 3.2.8 on 2021-11-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastChangeDate', models.DateTimeField(blank=True, null=True)),
                ('supplierArticle', models.CharField(max_length=20, null=True)),
                ('techSize', models.CharField(max_length=20, null=True)),
                ('barcode', models.CharField(blank=True, max_length=20)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('totalPrice', models.IntegerField(blank=True, default=0, null=True)),
                ('discountPercent', models.PositiveIntegerField(blank=True, null=True)),
                ('warehouseName', models.CharField(max_length=20, null=True)),
                ('oblast', models.CharField(max_length=20, null=True)),
                ('incomeID', models.IntegerField(blank=True, null=True)),
                ('odid', models.BigIntegerField(blank=True, default=0, null=True)),
                ('nmId', models.PositiveIntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('is_cancel', models.BooleanField(default=0)),
                ('cancel_dt', models.DateTimeField(blank=True, null=True)),
                ('gNumber', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastChangeDate', models.DateTimeField(blank=True, null=True)),
                ('supplierArticle', models.CharField(max_length=20, null=True)),
                ('techSize', models.CharField(blank=True, max_length=20)),
                ('barcode', models.CharField(blank=True, max_length=20)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('totalPrice', models.IntegerField(blank=True, default=0, null=True)),
                ('discountPercent', models.PositiveIntegerField(blank=True, null=True)),
                ('isSupply', models.BooleanField(blank=True, null=True)),
                ('isRealization', models.BooleanField(blank=True, null=True)),
                ('orderId', models.BigIntegerField(blank=True, default=0, null=True)),
                ('promoCodeDiscount', models.PositiveIntegerField(blank=True, null=True)),
                ('warehouseName', models.CharField(blank=True, max_length=20)),
                ('countryName', models.CharField(blank=True, max_length=20)),
                ('oblastOkrugName', models.CharField(blank=True, max_length=20)),
                ('regionName', models.CharField(blank=True, max_length=20)),
                ('incomeID', models.IntegerField(blank=True, default=0, null=True)),
                ('saleID', models.CharField(max_length=20, null=True)),
                ('odid', models.BigIntegerField(blank=True, default=0, null=True)),
                ('spp', models.PositiveIntegerField(blank=True, null=True)),
                ('forPay', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('finishedPrice', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('priceWithDisc', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('nmId', models.PositiveIntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('IsStorno', models.BooleanField(blank=True, null=True)),
                ('gNumber', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
