# Generated by Django 3.2.8 on 2021-11-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_cancel',
            new_name='isCancel',
        ),
    ]
