# Generated by Django 3.2.8 on 2021-11-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0002_rename_is_cancel_order_iscancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='number',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер'),
        ),
    ]
