# Generated by Django 3.2.8 on 2021-11-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0003_alter_sale_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='barcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='nmId',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество продаж'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='spp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена СПП'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='subject',
            field=models.CharField(blank=True, max_length=20, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='techSize',
            field=models.CharField(blank=True, max_length=20, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='totalPrice',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена без скидки'),
        ),
    ]
